### ISSUE TITLE
Usermin login from Webmin error

### ISSUE THREAD

**Issue by brad1001** [authentic-theme/authentic-theme#1357]
Hi there 
Hope all is well

When trying to login to Usermin via the edit users screen in Virtualmin  it redirects you back to the main Webmin screen .

I have this issue using Authentic theme version 19.33.

I have just tested this on another server with Authentic theme version 19.32 Beta 4 - there is no issue but as soon as I forced a theme update to 19.33 the issue appeared.

Kind Regards
Brad

**Comment by rostovtsev** [comment]
Hi,

Yes, there was a bug but it's fixed now.

Thank you for reporting.

**Comment by brad1001** [comment]
Hi 

Thank you very much for your reply and letting me know. I will await the new version

I did try 19.34 Beta8 which does still have the bug.

Kind Regards
Brad

**Comment by rostovtsev** [comment]
Brad, it seems like your browser doesn't clear cache.

Hit _Ctrl+Shift+R_ to force reload the browser's cache. Try incognito window at last.

It should work. 

Please report back.

**Comment by brad1001** [comment]
Hi
Thank you for your reply  - you are absolutely right 19.34 Beta8 is working as expected.
Kind Regards
Brad
